### PR TITLE
Fix issue where system-ingestible outputs were humanised(comma separated) leading to a breaking change in Steampipe. Closes #709

### LINKED ISSUE #709: System-ingestible formats should not be human readable
System-ingestible formats should not be human-readable; only pretty formats like table, line, pretty, plain should be made more human-readable (e.g. adding commas to numbers)

Bug in steampipe - https://github.com/turbot/steampipe/issues/4525

### PR DESCRIPTION
**Pull request by pskrbasu**
Values are now more human-readable (e.g. adding commas to numbers).

This PR fixes the issue where system ingestible formats like CSV, JSON and snapshot also had this change - which caused a breaking change in Steampipe.

### CODE REVIEW

File: querydisplay/column.go [hunk 1]
```diff
@@ -33,7 +30,10 @@ func columnNames(columns []*queryresult.ColumnDef) []string {
 	return colNames
 }
 
-type columnValueSettings struct{ nullString string }
+type columnValueSettings struct {
```
Comment (kaidaguerre) [inline querydisplay/column.go]: rename to columnValueConfig

File: querydisplay/display.go [hunk 2]
```diff
@@ -321,7 +321,7 @@ func displayLine[T queryresult.TimingContainer](ctx context.Context, result *que
 
 	// define a function to display each row
 	rowFunc := func(row []interface{}, result *queryresult.Result[T]) {
-		recordAsString, _ := ColumnValuesAsString(row, result.Cols)
+		recordAsString, _ := ColumnValuesAsString(row, result.Cols, WithHumanisedString(true))
```
Comment (kaidaguerre) [inline querydisplay/display.go:325]: comment for option

File: querydisplay/display.go [hunk 3]
```diff
@@ -423,7 +423,7 @@ func displayTable[T queryresult.TimingContainer](ctx context.Context, result *qu
 		}
 		displayRowCount++
 
-		rowAsString, _ := ColumnValuesAsString(row, result.Cols)
+		rowAsString, _ := ColumnValuesAsString(row, result.Cols, WithHumanisedString(true))
```
Comment (kaidaguerre) [inline querydisplay/display.go:428]: comment for option

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
